# Generated by Django 5.1 on 2024-10-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportdetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='importdetail',
            name='price',
        ),
    ]
