# Generated by Django 5.1 on 2024-10-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_exportdetail_price_remove_importdetail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='import',
            name='amount',
        ),
    ]
