# Generated by Django 5.1 on 2024-10-20 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_export_amount_remove_import_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='created_date',
            new_name='required_date',
        ),
        migrations.RemoveField(
            model_name='export',
            name='note',
        ),
        migrations.AddField(
            model_name='export',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='exported_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã xuất', 'Đã xuất'), ('Không xuất', 'Không xuất')], default='Chờ duyệt', max_length=20),
        ),
        migrations.AddField(
            model_name='export',
            name='store_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
