# Generated by Django 5.1 on 2024-10-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_created_date_export_required_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='slug',
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
